[Version]
Class=IExpress
SEDVersion=3
[Options]
PackagePurpose=InstallFree
ShowInstallProgramWindow=0
HideExtractAnimation=1
UseLongFileName=1
InsideCompressed=1
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\Chixi\Documents\Projects\Connect4butdifferent\Connect 4.exe
FriendlyName=Connect 4
AppLaunched=game.exe
PostInstallCmd=<None>
AdminQuietInstCmd=
UserQuietInstCmd=
SourceFiles=SourceFiles
[SourceFiles]
SourceFiles0=C:\Users\Chixi\Documents\Projects\Connect4butdifferent\pack_dir
[SourceFiles0]
%File0%=
%File1%=
%File2%=
%File3%=
%File4%=
%File5%=
%File6%=
%File7%=
[SourceFiles0]
%File0%=""
%File1%=""
%File2%=""
%File3%=""
%File4%=""
%File5%=""
%File6%=""
%File7%=""
